"""add github_full_name to repository

Revision ID: ec9d0b4f16f9
Revises: d8880ee3c9d7
Create Date: 2026-02-10 21:14:17.796998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec9d0b4f16f9'
down_revision: Union[str, Sequence[str], None] = 'd8880ee3c9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('github_full_name', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_repository_github_full_name'), 'repository', ['github_full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_github_full_name'), table_name='repository')
    op.drop_column('repository', 'github_full_name')
    # ### end Alembic commands ###
